CREATE TABLE IF NOT EXISTS riders (
	rider_id UUID PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
	current_location_id UUID REFERENCES locations(location_id),
	rating DECIMAL(3, 2) DEFAULT 0.0,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_riders_updated_at BEFORE
UPDATE
	ON riders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();