CREATE TABLE IF NOT EXISTS wallets (
	wallet_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID UNIQUE REFERENCES users(user_id) ON DELETE CASCADE,
	balance DECIMAL(10, 2) DEFAULT 0.00,
	amount_owed DECIMAL(10, 2) DEFAULT 0.00,
	currency VARCHAR(3) DEFAULT 'EGP',
	status wallet_status DEFAULT 'active',
	last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);